# Machine Learning Fundamentals Workshop

Welcome! This notebook guides you through practical exercises in `Python, NumPy, Pandas, Matplotlib, and scikit-learn`.  
Follow each section, run the code cells, and complete the exercises to build your ML skills.

## 1. Python & NumPy Basics

NumPy is the foundation for numerical computing in Python.


In [1]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Exercise: Create a 3x3 matrix and calculate the sum of each column.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)
print("Column sums:", np.sum(matrix, axis=0))


Array: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Column sums: [12 15 18]


## 2. Pandas for Data Analysis

Pandas makes working with tabular data easy.


In [ ]:
import pandas as pd

# Load Titanic dataset (from seaborn for simplicity)
import seaborn as sns
titanic = sns.load_dataset('titanic')
print(titanic.head())

# Check for missing values
print(titanic.isnull().sum())

# Exercise: Count unique values in the 'embarked' column and fill missing values with the mode.
print("Unique Embarked:", titanic['embarked'].unique())
titanic['embarked'].fillna(titanic['embarked'].mode()[0], inplace=True)


## 3. Data Visualization

Matplotlib helps visualize data distributions and relationships.


In [ ]:
import matplotlib.pyplot as plt

# Histogram of passenger age
plt.hist(titanic['age'].dropna(), bins=20, color='skyblue')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

# Exercise: Create a scatter plot of 'fare' vs 'age'.
plt.scatter(titanic['age'], titanic['fare'], alpha=0.5)
plt.xlabel('Age')
plt.ylabel('Fare')
plt.title('Fare vs Age')
plt.show()


## Exercise 1:
A. `Numpy` exercise
1. Create and Manipulate Arrays
- Create a 1D NumPy array of numbers from 0 to 9.
- Reshape it into a 2D array with 2 rows.
- Calculate the sum of all elements and the mean of each row.

2. Array Slicing and Indexing
- Given an array arr = np.arange(20), extract all even numbers.
- Replace all values greater than 10 with -1.

3. Mathematical Operations
- Generate a 3x3 matrix of random integers between 1 and 10.
- Compute the element-wise square of the matrix.
- Find the maximum value in each column.

B. `Pandas` exercise
1. DataFrame Creation and Exploration
- Create a DataFrame with columns: Name, Age, Score.
- Add at least 5 rows of sample data.
- Display summary statistics and check for missing values.

2. Data Selection and Filtering
- From the DataFrame above, select all rows where Score is greater than 80.
- Add a new column called Passed that is True if Score ≥ 60, else False.

3. Data Cleaning
- Introduce some missing values in the Age column.
- Fill missing ages with the mean age.
- Remove any duplicate rows from the DataFrame.

C. `Matplotlib` exercise
1. Basic Plotting
- Plot a line graph showing the squares of numbers from 0 to 10.
- Add axis labels and a title.

2. Histogram
- Plot a line graph showing the squares of numbers from 0 to 10.
- Add axis labels and a title.

3. Scatter plot
- Use the Pandas `DataFrame` from earlier.
- Plot a scatter plot of `Age` vs. `Score`.
- Color points by the value in the Passed column.


In [ ]:
# Your code here

## 4. Linear Regression Example (Diabetes Dataset)

Linear regression predicts continuous values.


In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import pandas as pd

#Load and inspect
cal = fetch_california_housing(as_frame=True)
X, y = cal.data, cal.target * 100_000        # convert to dollars for readability

#Train / test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Fit
model = LinearRegression()
model.fit(X_train, y_train)

#Evaluate
y_pred = model.predict(X_test)
print("MSE :", mean_squared_error(y_test, y_pred))
print("MAE :", mean_absolute_error(y_test, y_pred))
print("R²  :", r2_score(y_test, y_pred))


In [ ]:
import matplotlib.pyplot as plt

# 1. Compute residuals
residuals = y_test - y_pred

# 2. Residual-vs-Predicted scatter plot
plt.figure(figsize=(7,4))
# code here
plt.show()

# 3. Histogram (and KDE) of residuals
plt.figure(figsize=(7,4))
# code here
plt.show()


## 5. Logistic Regression Example (Iris Dataset)

Logistic regression is used for classification tasks.


In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load data
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
clf = LogisticRegression(max_iter=200)
clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Exercise: Change test_size to 0.3 and observe the effect on accuracy.


## Exercise 2 - Mini Project

A. [Abalone Dataset](https://www.kaggle.com/datasets/rodolfomendes/abalone-dataset) — Regression Task

1.  Project Overview:

- Goal: Predict the age of abalone (number of rings) based on physical measurements.
- Task Type: Regression
- Dataset Source: UCI Machine Learning Repository

1.  Dataset Features
- Sex: Categorical (M, F, I)
- Length, Diameter, Height: Numeric (physical measurements)
- Whole weight, Shucked weight, Viscera weight, Shell weight: Numeric (weights in grams)
- Rings: Integer (target variable; age = rings + 1.5)

In [ ]:
# 1. Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 2. Load the Abalone dataset


# 3. Data preprocessing
# Encode categorical 'Sex' feature using OneHotEncoder


# 4. Define features and target


# 5. Split data into training and test sets


# 6. Feature scaling (optional but recommended for regression)


# 7. Train a Linear Regression model


# 8. Make predictions and evaluate




B. [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data) — Classification Task
1. Project Overview
- Goal: Predict whether a tumor is malignant or benign based on cell features.
- Task Type: Classification
- Dataset Source: Built into scikit-learn

2. Dataset Features
- 30 numeric features (mean, standard error, and worst of various cell characteristics)
- Target: Diagnosis (0 = malignant, 1 = benign)

In [ ]:
# 1. Import required libraries
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd

# 2. Load the Breast Cancer Wisconsin dataset
data = load_breast_cancer()


# 3. Convert to DataFrame for exploration (optional)


# 4. Train/test split


# 5. Feature scaling (recommended)


# 6. Train a Logistic Regression model


# 7. Make predictions and evaluate


# 8. Exercise: Try other classifiers (e.g., DecisionTreeClassifier, RandomForestClassifier, SVC)
